# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odev2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='firstt_name',
        ),
    ]
